Made Calculator
rahul72parihar/calculator pull request #1
Opened 2023-02-21 10:12 UTC by rahul72parihar

Javascript
- made 3 variable for num1, operator and num2
- different function for clear and equal 
- made a display with heading and textContent to display

2023-02-21 13:41 UTC, rahul72parihar commented on index.js
> +console.log("render");
Remove console.log

2023-02-21 13:41 UTC, rahul72parihar commented on index.js
> +let op = null;
give better name to op

2023-02-21 13:41 UTC, rahul72parihar commented on styles.css
> +*,
add newline after each selector

2023-02-21 14:10 UTC, balwant-jtc requested changes

2023-02-21 14:10 UTC, balwant-jtc commented on index.js
> +let mainOperator = null;
Use array destructuring to initialize the variables num1, num2, and mainOperator to null.
`let [num1, num2, mainOperator] = [null, null, null];`

2023-02-21 14:10 UTC, balwant-jtc commented on index.js
> +function handleNumber(num) {
Can you simplify this function, its hard to read currently?

2023-02-21 14:10 UTC, balwant-jtc commented on index.js
> +    display.textContent = num1 + mainOperator + num2;
Use template literals to concate multiple strings.

2023-02-21 14:10 UTC, balwant-jtc commented on index.js
> +  num2 = null;
`[num2, mainOperator] = [null, null];`

2023-02-21 14:10 UTC, balwant-jtc commented on index.js
> +  num1 = null;
[num1, mainOperator, num2] = [null, null, null];

2023-02-21 14:10 UTC, balwant-jtc commented on index.js
> +  else if (mainOperator === "-") num1 -= num2;
use `switch` here instead of `if` to make it more readable

2023-02-24 06:21 UTC, balwant-jtc approved these changes

2023-02-24 06:23 UTC, merged